// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: telemetry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RobotTelemetry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs     int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RobotId         string                 `protobuf:"bytes,3,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	JointPositions  []float32              `protobuf:"fixed32,4,rep,packed,name=joint_positions,json=jointPositions,proto3" json:"joint_positions,omitempty"`
	JointVelocities []float32              `protobuf:"fixed32,5,rep,packed,name=joint_velocities,json=jointVelocities,proto3" json:"joint_velocities,omitempty"`
	JointEfforts    []float32              `protobuf:"fixed32,6,rep,packed,name=joint_efforts,json=jointEfforts,proto3" json:"joint_efforts,omitempty"`
	CameraFrames    map[string][]byte      `protobuf:"bytes,7,rep,name=camera_frames,json=cameraFrames,proto3" json:"camera_frames,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SensorReadings  map[string]float32     `protobuf:"bytes,8,rep,name=sensor_readings,json=sensorReadings,proto3" json:"sensor_readings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	BatteryLevel    float32                `protobuf:"fixed32,9,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	ErrorFlags      []string               `protobuf:"bytes,10,rep,name=error_flags,json=errorFlags,proto3" json:"error_flags,omitempty"`
	EndEffectorPose *Pose                  `protobuf:"bytes,11,opt,name=end_effector_pose,json=endEffectorPose,proto3" json:"end_effector_pose,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RobotTelemetry) Reset() {
	*x = RobotTelemetry{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotTelemetry) ProtoMessage() {}

func (x *RobotTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotTelemetry.ProtoReflect.Descriptor instead.
func (*RobotTelemetry) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *RobotTelemetry) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *RobotTelemetry) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RobotTelemetry) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *RobotTelemetry) GetJointPositions() []float32 {
	if x != nil {
		return x.JointPositions
	}
	return nil
}

func (x *RobotTelemetry) GetJointVelocities() []float32 {
	if x != nil {
		return x.JointVelocities
	}
	return nil
}

func (x *RobotTelemetry) GetJointEfforts() []float32 {
	if x != nil {
		return x.JointEfforts
	}
	return nil
}

func (x *RobotTelemetry) GetCameraFrames() map[string][]byte {
	if x != nil {
		return x.CameraFrames
	}
	return nil
}

func (x *RobotTelemetry) GetSensorReadings() map[string]float32 {
	if x != nil {
		return x.SensorReadings
	}
	return nil
}

func (x *RobotTelemetry) GetBatteryLevel() float32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *RobotTelemetry) GetErrorFlags() []string {
	if x != nil {
		return x.ErrorFlags
	}
	return nil
}

func (x *RobotTelemetry) GetEndEffectorPose() *Pose {
	if x != nil {
		return x.EndEffectorPose
	}
	return nil
}

type Pose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Qw            float32                `protobuf:"fixed32,4,opt,name=qw,proto3" json:"qw,omitempty"`
	Qx            float32                `protobuf:"fixed32,5,opt,name=qx,proto3" json:"qx,omitempty"`
	Qy            float32                `protobuf:"fixed32,6,opt,name=qy,proto3" json:"qy,omitempty"`
	Qz            float32                `protobuf:"fixed32,7,opt,name=qz,proto3" json:"qz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pose) Reset() {
	*x = Pose{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pose) ProtoMessage() {}

func (x *Pose) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pose.ProtoReflect.Descriptor instead.
func (*Pose) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Pose) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pose) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Pose) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Pose) GetQw() float32 {
	if x != nil {
		return x.Qw
	}
	return 0
}

func (x *Pose) GetQx() float32 {
	if x != nil {
		return x.Qx
	}
	return 0
}

func (x *Pose) GetQy() float32 {
	if x != nil {
		return x.Qy
	}
	return 0
}

func (x *Pose) GetQz() float32 {
	if x != nil {
		return x.Qz
	}
	return 0
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\ttelemetry\"\x97\x05\n" +
	"\x0eRobotTelemetry\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\brobot_id\x18\x03 \x01(\tR\arobotId\x12'\n" +
	"\x0fjoint_positions\x18\x04 \x03(\x02R\x0ejointPositions\x12)\n" +
	"\x10joint_velocities\x18\x05 \x03(\x02R\x0fjointVelocities\x12#\n" +
	"\rjoint_efforts\x18\x06 \x03(\x02R\fjointEfforts\x12P\n" +
	"\rcamera_frames\x18\a \x03(\v2+.telemetry.RobotTelemetry.CameraFramesEntryR\fcameraFrames\x12V\n" +
	"\x0fsensor_readings\x18\b \x03(\v2-.telemetry.RobotTelemetry.SensorReadingsEntryR\x0esensorReadings\x12#\n" +
	"\rbattery_level\x18\t \x01(\x02R\fbatteryLevel\x12\x1f\n" +
	"\verror_flags\x18\n" +
	" \x03(\tR\n" +
	"errorFlags\x12;\n" +
	"\x11end_effector_pose\x18\v \x01(\v2\x0f.telemetry.PoseR\x0fendEffectorPose\x1a?\n" +
	"\x11CameraFramesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1aA\n" +
	"\x13SensorReadingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"p\n" +
	"\x04Pose\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x0e\n" +
	"\x02qw\x18\x04 \x01(\x02R\x02qw\x12\x0e\n" +
	"\x02qx\x18\x05 \x01(\x02R\x02qx\x12\x0e\n" +
	"\x02qy\x18\x06 \x01(\x02R\x02qy\x12\x0e\n" +
	"\x02qz\x18\a \x01(\x02R\x02qzB-Z+github.com/dojo-harvester/backend/pkg/protob\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_telemetry_proto_goTypes = []any{
	(*RobotTelemetry)(nil), // 0: telemetry.RobotTelemetry
	(*Pose)(nil),           // 1: telemetry.Pose
	nil,                    // 2: telemetry.RobotTelemetry.CameraFramesEntry
	nil,                    // 3: telemetry.RobotTelemetry.SensorReadingsEntry
}
var file_telemetry_proto_depIdxs = []int32{
	2, // 0: telemetry.RobotTelemetry.camera_frames:type_name -> telemetry.RobotTelemetry.CameraFramesEntry
	3, // 1: telemetry.RobotTelemetry.sensor_readings:type_name -> telemetry.RobotTelemetry.SensorReadingsEntry
	1, // 2: telemetry.RobotTelemetry.end_effector_pose:type_name -> telemetry.Pose
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
