# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"\xe6\x03\n\x0eRobotTelemetry\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x03\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x10\n\x08robot_id\x18\x03 \x01(\t\x12\x17\n\x0fjoint_positions\x18\x04 \x03(\x02\x12\x18\n\x10joint_velocities\x18\x05 \x03(\x02\x12\x15\n\rjoint_efforts\x18\x06 \x03(\x02\x12\x42\n\rcamera_frames\x18\x07 \x03(\x0b\x32+.telemetry.RobotTelemetry.CameraFramesEntry\x12\x46\n\x0fsensor_readings\x18\x08 \x03(\x0b\x32-.telemetry.RobotTelemetry.SensorReadingsEntry\x12\x15\n\rbattery_level\x18\t \x01(\x02\x12\x13\n\x0b\x65rror_flags\x18\n \x03(\t\x12*\n\x11\x65nd_effector_pose\x18\x0b \x01(\x0b\x32\x0f.telemetry.Pose\x1a\x33\n\x11\x43\x61meraFramesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x1a\x35\n\x13SensorReadingsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"W\n\x04Pose\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\n\n\x02qw\x18\x04 \x01(\x02\x12\n\n\x02qx\x18\x05 \x01(\x02\x12\n\n\x02qy\x18\x06 \x01(\x02\x12\n\n\x02qz\x18\x07 \x01(\x02\x42-Z+github.com/dojo-harvester/backend/pkg/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/dojo-harvester/backend/pkg/proto'
  _globals['_ROBOTTELEMETRY_CAMERAFRAMESENTRY']._loaded_options = None
  _globals['_ROBOTTELEMETRY_CAMERAFRAMESENTRY']._serialized_options = b'8\001'
  _globals['_ROBOTTELEMETRY_SENSORREADINGSENTRY']._loaded_options = None
  _globals['_ROBOTTELEMETRY_SENSORREADINGSENTRY']._serialized_options = b'8\001'
  _globals['_ROBOTTELEMETRY']._serialized_start=31
  _globals['_ROBOTTELEMETRY']._serialized_end=517
  _globals['_ROBOTTELEMETRY_CAMERAFRAMESENTRY']._serialized_start=411
  _globals['_ROBOTTELEMETRY_CAMERAFRAMESENTRY']._serialized_end=462
  _globals['_ROBOTTELEMETRY_SENSORREADINGSENTRY']._serialized_start=464
  _globals['_ROBOTTELEMETRY_SENSORREADINGSENTRY']._serialized_end=517
  _globals['_POSE']._serialized_start=519
  _globals['_POSE']._serialized_end=606
# @@protoc_insertion_point(module_scope)
